function plot_rawfft(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-May-2017 19:02:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
box(axes1,'on')

% Create multiple lines using matrix input to plot
plot(X1,YMatrix1,'LineWidth',1);

% Create xlabel
xlabel('Physical Frequency (Hz)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-25 25]);
% Set the remaining axes properties
set(axes1,'FontSize',16);
