function plot_thresh(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-May-2017 20:50:23

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'LineWidth',2,'LineStyle','--');
set(plot1(2),'LineWidth',3);

% Create xlabel
xlabel('Time (s)');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16);
